Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = []
path = [cwd + '/inc']
libs = []
libpath = [cwd + '/libs']

if rtconfig.CROSS_TOOL == 'gcc':
    libs += ['rt_ota_armcm7_noalgo_0.2.3_gcc']
elif rtconfig.CROSS_TOOL == 'keil':
    libs += ['librt_ota_armcm7_noalgo_0.2.3_keil']

src += ['src/rtota_update.c']

group = DefineGroup('rt_ota', src, depend = ['ART_PI_USING_OTA_LIB'], CPPPATH = path, LIBS = libs, LIBPATH = libpath)

Return('group')
