[package]
name = "flowsdk-no-io-client"
version = "0.1.0"
edition = "2021"
publish = false
license = "Apache-2.0"

[dependencies]
flowsdk = { version = "=0.6.2", default-features = false, features = ["strict-protocol-compliance"] }
mio = { version = "1", features = ["net", "os-poll"] }
clap = { version = "4.5", features = ["derive"] }
